#!/bin/bash
export PATH=$HOME/.local/bin:$PATH
export CC=$HOME/.local/bin/gcc
export CXX=$HOME/.local/bin/g++
export LD_LIBRARY_PATH=$HOME/.local/lib64:$LD_LIBRARY_PATH
source /home/itep/skobliakov/app/CERN/geant4-v11.4.3-install/bin/geant4.sh
cd $HOME/FLUX/build/
cmake ..
make
./Mdet
